function(configure_lto TARGET_NAME)
    if (MERINGUE_LTO)
        cmake_policy(SET CMP0069 NEW)
        set_property(TARGET ${TARGET_NAME} PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)
    endif()
endfunction()
